services:
  - type: web
    name: funda-scraper-api
    env: python
    plan: free
    region: frankfurt
    buildCommand: >
      pip install -r requirements.txt &&
      python -m playwright install --with-deps chromium
    startCommand: "uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
