services:
  - type: web
    name: fu-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt && \
      PLAYWRIGHT_BROWSERS_PATH=0 python -m playwright install chromium
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
    autoDeploy: true
